#!/bin/sh
#
# /etc/rc.d/connamnd: start/stop connman daemon
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/connmand

case $1 in
	start)
		$SSD --start --exec $PROG
		;;
	stop)
		$SSD --stop --retry 10 --exec $PROG
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		$SSD --status --exec $PROG
		case $? in
		0) echo "$PROG is running with pid $(cat $PID)" ;;
		1) echo "$PROG is not running but the pid file $PID exists" ;;
		3) echo "$PROG is not running" ;;
		4) echo "Unable to determine the program status" ;;
		esac
		;;
	*)
		echo "Usage: $0 [start|stop|restart|status]"
		;;
esac

# End of file
