#!/bin/sh
#
# /etc/rc.d/wpa_supplicant: start/stop wpa_supplicant
#

SSD=/sbin/start-stop-daemon
PROG=/usr/sbin/wpa_supplicant
PID=/var/run/wpa_supplicant
OPTS="-us"

case $1 in
start)
	$SSD --start -bm --pidfile $PID --exec $PROG -- $OPTS
	;;
stop)
	$SSD --stop --remove-pidfile --retry 10 --pidfile $PID
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	$SSD --status --pidfile $PID
	case $? in
	0) echo "$PROG is running" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG is not running" ;;
	4) echo "Unable to determine the program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# End of file
